version: 2
jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: circleci/php:5.6-node
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: jitterbug_testing
      - image: circleci/solr:7.2.1

    working_directory: ~/jitterbug

    steps:
      - checkout
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Install PHP exts
          command: |
            sudo docker-php-ext-install zip
            sudo docker-php-ext-install pdo_mysql
            sudo apt install -y mysql-client
            sudo apt-get install libldap2-dev -y
            sudo rm -rf /var/lib/apt/lists/*
            sudo docker-php-ext-configure ldap --with-libdir=lib/x86_64-linux-gnu/
            sudo docker-php-ext-install ldap

      - run: sudo composer self-update
      - run:
          name: Copy Circle CI version of .env.testing
          command: cp .env.testing.circleci .env.testing

      - run:
          name: Install Solr
          command: |
            cd ~
            sudo wget --no-verbose http://archive.apache.org/dist/lucene/solr/7.2.1/solr-7.2.1.tgz
            tar xzf solr-7.2.1.tgz solr-7.2.1/bin/install_solr_service.sh --strip-components=2
            ./install_solr_service.sh solr-7.2.1.tgz
            cd /opt/solr
            bin/solr start
            cd /jitterbug

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
      - run:
          name: Migrate DB
          command: |
            php artisan config:cache --env=testing
            php artisan migrate --env=testing --force
      - run:
          name: Wait for Solr
          command: dockerize -wait tcp://127.0.0.1:8983 -timeout 120s
      - run:
          name: Run Tests
          command: ./vendor/bin/phpunit


workflows:
  version: 2
  notify_deploy:
    jobs:
      - build