  <script type="text/javascript" src="{!! asset('js/jquery.min.js') !!}"></script>
  <script type="text/javascript" src="{!! asset('js/tether.min.js') !!}"></script>
  <script type="text/javascript" src="{!! asset('js/bootstrap-datepicker.min.js') !!}"></script>
  <script type="text/javascript" src="{!! asset('js/charts.loader.min.js') !!}"></script>
  <script type="text/javascript" src="{!! asset('js/chosen.jquery.min.js') !!}"></script>
  <script type="text/javascript" src="{!! asset('js/jquery.dataTables.min.js') !!}"></script>
  <script type="text/javascript" src="{!! asset('js/vendor.js') !!}"></script>
  <script type="text/javascript" src="{!! asset('js/app.js') !!}"></script>
  <script type="text/javascript" src="{!! asset('js/router.js') !!}"></script>
